/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/pc/Footer copy.vue')['default']
    EndDialog: typeof import('./src/components/EndDialog.vue')['default']
    Foote: typeof import('./src/components/pc/Foote.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LoginDialog: typeof import('./src/components/LoginDialog.vue')['default']
    RedEnvelopeDialog: typeof import('./src/components/RedEnvelopeDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScanDialog: typeof import('./src/components/ScanDialog.vue')['default']
    TestComp: typeof import('./src/components/TestComp.vue')['default']
    TipDialog: typeof import('./src/components/TipDialog.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanDialog: typeof import('vant/es')['Dialog']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
  }
}
