name: Build Lilith Test and Deploy To Aliyun ECS

on:                               
  pull_request:
    branches: [ main ]
    types:
      - closed

jobs:                             
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest        
    steps:                        
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      with:
        version: '7'

    - name: Install dependencies
      run: pnpm install

    - name: Build static
      run: pnpm build

    - name: Deploy to net0backend server        
      uses: easingthemes/ssh-deploy@v3.0.0      
      env:
        SSH_PRIVATE_KEY: ${{ secrets.BACKEND_SSH_KEY }} 
        ARGS: "-avzr --delete"
        SOURCE: "dist/*"
        REMOTE_HOST: ${{ secrets.BACKEND_HOST }}
        REMOTE_USER: ${{ secrets.BACKEND_USER }}
        TARGET: "/var/www/lilith/"
